### ISSUE TITLE
NoClip Lines and Rectangles Not Displaying at y = 240

### ISSUE THREAD

**Issue by spenceboy98** [CE-Programming/libraries#11]
When I use gc_NoClipRectangle(0, 0, 36, 240); it doesn't display the rectangle at all. I tried making the Rectangle a pixel shorter and drawing a Horizontal line where the missing line was, but the line didn't display either. Vertical Lines draw, but with a length of 240, the last pixel is not displaying. For now I'm just using the Clipped routines and it's working fine.

**Comment by MateoConLechuga** [comment]
Well, the question is wether or not you want it based off of pixels, or bounds to be inclusive. 0-240 means 241 pixels, which goes offscreen, thus the rectangle is not drawn. 0-239 works because that means it is 240 pixels tall.

**Comment by jacobly0** [comment]
Fixed with 002cae322bcb5635ed9ffacb35d97b75d11199aa.
