### ISSUE TITLE
Consistent error

### ISSUE THREAD

**Issue by LuminousRain** [CE-Programming/libraries#28]
Error tells me to come here for library file GRAPHC, but no such file exists. Could there be a typo between GRAPHX and GRAPHC?

**Comment by mateoconlechuga** [comment]
No; the graphc library was discontinued and is no longer supported. Some developers have not maintained their programs; which causes this. You can download graphc library here though.

https://github.com/CE-Programming/libraries/releases/tag/v7.1

Be sure to just get the graphc library there; and use the latest release for all other libraries.
