### ISSUE TITLE
[HELP] Installed the lastest version and i can't see graphs anymore.

### ISSUE THREAD

**Issue by Kacaline** [CE-Programming/libraries#31]
I don't know what to do, i tried to install the 7.7 version and also other to test but it seems i can't load any graphs anymore, it just displays a black screen. 
Could someone help me please :)

**Comment by mateoconlechuga** [comment]
Have you tried reseting your calculator and retransmitting the files? We are a little confused by what exactly is black. Would you mind uploading any pictures to help us diagnose the issue?

**Comment by Kacaline** [comment]
Oops wanted to write blank screen. 
![graph blank screen](https://user-images.githubusercontent.com/33043319/31934586-d0dace78-b8ac-11e7-90d1-dc940393a908.png)

**Comment by Kacaline** [comment]
Well, i managed to display what i needed in the graph menu by modifying options in the "format" menu. Which looks like this now : 
![capturer3-1508860970907](https://user-images.githubusercontent.com/33043319/31954271-740f0590-b8e5-11e7-8a9c-fd58edbb2f55.png)
Definetely not what i used to have by default but it's fine like that.

**Comment by mateoconlechuga** [comment]
Looks like a program modified your settings. Just press the reset button on the back of your calculator to reset the option back to the default. :)
