### ISSUE TITLE
Will not UnArchive Anything

### ISSUE THREAD

**Issue by programmer2514** [CE-Programming/libraries#33]
I have written a program using these libraries for Archiving/UnArchiving programs, but it cannot UnArchive anything. I have tested for bugs in the program and the compiler, and came to the conclusion that the C libraries were causing it. Please tell me if I am wrong or if this issue can even be fixed. Thank you

**Comment by mateoconlechuga** [comment]
You are doing something wrong.

**Comment by LAX18** [comment]
He is missing one important factor:
This is in ICE

I told him it was not ICE's issue because I told @PeterTillema about it and he said it was a C Toolchain issue.

**Comment by npease18** [comment]
He is missing one important factor:
This is in ICE

I told him it was not ICE's issue because I told @PeterTillema about it and he said it was a C Toolchain issue.

**Comment by mateoconlechuga** [comment]
It's most certainly an ICE issue. Closing for now.
