### ISSUE TITLE
How to fix "Need LibLoad" problem on Mac

### ISSUE THREAD

**Issue by LUcIDaMa** [CE-Programming/libraries#36]
How??

**Comment by adriweb** [comment]
1. Download the `clibs.8xg` file from the latest release: https://github.com/CE-Programming/libraries/releases/latest
2. Transfer that file with [TI Connect CE](https://education.ti.com/en/products/computer-software/ti-connect-ce-sw) or TILP.

Then whatever programs requiring LibLoad should work.

**Comment by LUcIDaMa** [comment]
ok
