### ISSUE TITLE
Error: invalid

### ISSUE THREAD

**Issue by tarneaux** [CE-Programming/libraries#37]
I installed the library and the program, but when i try to run it I get [this](https://ibb.co/MMR9t03)
Any help?

**Comment by Jeffitus** [comment]
You're probably on OS version 5.5.1 or higher, which disables assembly programs. Luckily you can use arTIfiCE to fix that: https://yvantt.github.io/arTIfiCE/

**Comment by tarneaux** [comment]
Thanks, worked!
