### ISSUE TITLE
Where are fatdrvce/usbdrvce

### ISSUE THREAD

**Issue by Luanism** [CE-Programming/libraries#38]
I need it for Cesium

**Comment by NonstickAtom785** [comment]
You just need a usb device with the appropriate adapters. 

Do a quick search on `USB A Female to USB Mini 5pin Male Adapter`

Then USBDRVCE should be a simple library meant for assembly programs. I don't actually think it's a clib at the moment. I thought it was compiled in. But I did some digging around and found a branch with that name in the toolchain.

Here's the link to that:
[usbdrvce](https://github.com/CE-Programming/toolchain/tree/usbdrvce)

You may also want to know that you won't get many answers by asking in an old github repo. This repo is just for the libraries that got compiled at a certain date. There kinda static and don't change.

The developer posted another link in the readme on this repo:
![image](https://user-images.githubusercontent.com/36454623/136672863-d710fdc7-d888-49ae-a5b2-964059ef9728.png)

So most likely reading the readme will help you out a lot.
[The Readme](https://github.com/CE-Programming/libraries/blob/master/readme.md)

ALSO before you go I'd close the issue. It's not really an issue. Just saying.

**Comment by Marasme** [comment]
Hello everybody !

I am also looking for usbdrvce but I do not know how to get this library in 8xv format (for the ti-83 premium)...
Someone can help me ???

Thanks in advance.
(translated with google translate).

**Comment by adriweb** [comment]
USB support is being rewritten with many improvements, check back when a new version is released, I guess.

**Comment by Serial-Comma** [comment]
Same error, when I try to run it it tells me 'Missing Library: USBDRVCE' even though I already downloaded and transferred whatever was in the link provided(https://tiny.cc/clibs), any help?

84 plus ce btw

**Comment by Serial-Comma** [comment]
Change to my above, I didn't follow the instructions properly and read the README when installing Transfer. My bad. Perhaps put a 'Read the README' in the error screen if there's missing libraries

**Comment by mateoconlechuga** [comment]
These libraries are now available in the latest release :)
