### ISSUE TITLE
[fileio lib] ti_OpenVar doesn't seem to work

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/libraries#4]
@Snektron reported on #ez80-dev that `ti_Open("A", "w");` works but  `ti_OpenVar("A", "w", AppVar);` does not.
In fact, `ti_OpenVar` doesn't open programs either.

**Comment by mateoconlechuga** [comment]
The issue is I counted from 1, not 0. Should be __frame_arg2, not __frame_arg3. Simple fix when I have a chance.

**Comment by mateoconlechuga** [comment]
Merged Pull Requested and updated new release with tag 1.3. Thanks! :)
