### ISSUE TITLE
ERROR: Missing Library

### ISSUE THREAD

**Issue by HiddeBeste** [CE-Programming/libraries#40]
When i open mario (oriam), using ARTIFICE, it gives the error: Missing Library (see photo).
I can run pacman, and i did install clibs. I do also use TI connect CE App for chrome OS, and used [commandblockguy's method](https://www.cemetech.net/forum/viewtopic.php?p=290727) to install protected programs. How can I fix this problem?
(i copied my old reddit post, it didnt get any reactions. I thought it was probably clibs)
photo: 
![ERROR: Missing Library](https://user-images.githubusercontent.com/62608499/200918461-3f6cbb87-2019-47bd-b130-c889c0e42823.png)

**Comment by mateoconlechuga** [comment]
You can install the libraries here: https://github.com/CE-Programming/libraries/releases/latest

Ensure you have the FILEIOC AppVar in the memory menu.
