### ISSUE TITLE
file ioc missing

### ISSUE THREAD

**Issue by WatchMeFadee** [CE-Programming/libraries#41]
when i try to send clibs to my calculator it simply dose not want to. i think is may be because it is a libload package. can anyone help me out because i cant play many of my games because of this error

**Comment by adriweb** [comment]
You have to use TI-Connect CE, then drag'n'drop the `clibs.8xg` file onto the calculator's name in the sidebar.

**Comment by WatchMeFadee** [comment]
i tried this using the chrome version (i am on a chromebook) and it says its on the calculator but i still get the same error when trying to launch the game

**Comment by adriweb** [comment]
Ah, clibs.8xg doesn't get auto-extracted by the chrome TI-Connect CE version then?

Out of curiosity, can you check if you can ungroup the clibs on the calculator itself and see if that solves the issue?
Check here for instructions: https://www.dummies.com/article/technology/electronics/graphing-calculators/how-to-group-and-ungroup-programs-on-the-ti-84-plus-160456/

**Comment by WatchMeFadee** [comment]
i tried to ungroup clibs but it didint come up on the calculator. if it helps i am using https://www.cemetech.net/forum/viewtopic.php?t=17238&start=0 
to send asm files to the calculator from my chromebook.

**Comment by adriweb** [comment]
That's fine for ASM programs, but clibs is a group so I guess you'll have to transfer each 8xv file individually (see attached zip file that you'll have to extract on your computer first) or get a non-chromebook computer to use TI-Connect CE or TILP.

Let's ping @commandblockguy anyway...

______________________

[clibs_each_8xv.zip](https://github.com/CE-Programming/libraries/files/10366954/clibs_each_8xv.zip)

**Comment by WatchMeFadee** [comment]
thank you so much for sending me the .zip file, it now works. i think the issue was that chrome locks files so the calculator could not interact with the chromebook, thanks for the help
