### ISSUE TITLE
Need older versions of graphix

### ISSUE THREAD

**Issue by ghost** [CE-Programming/libraries#43]
Hi, I am trying to run a game on my ti-84 plus ce, but it says that i need a different version of GRAPHIX. Is there already a site set up with older versions, or do I just have to get a different game?

**Comment by adriweb** [comment]
Which game is it?
And does it say GRAPHC or GRAPHX? 

If GRAPHX, it should work if you download the [latest release](https://github.com/CE-Programming/libraries/releases/latest), unless the program was built with a nightly version of the toolchain...

**Comment by ghost** [comment]
It says GRAPHX, but the latest release doesn't work. I have no idea what the nightly version is though.

**Comment by adriweb** [comment]
These are the nightly libraries: https://github.com/CE-Programming/toolchain/releases/download/nightly/clibs-nightly.8xg

**Comment by ghost** [comment]
Thanks, I'll try that and let you know how it goes.

**Comment by ghost** [comment]
![Capture 1](https://github.com/CE-Programming/libraries/assets/140832412/fd405b3b-215d-4bdc-aac5-57123cd47fe4)
Now it's showing this, not sure if this is an issue with GRAPHIX or not.

**Comment by adriweb** [comment]
Looks like you haven't properly sent all the libs (you need to drag'n'drop the 8xg file)

**Comment by ghost** [comment]
TI Connect CE doesn't do anything when I drag and drop. Might it be because I'm using a chromebook?

**Comment by adriweb** [comment]
I'm surprised it doesn't transfer the whole 8xg... that's weird.
Anyway try to get it transferred from a PC or Mac then 🤷‍♂️

**Comment by ghost** [comment]
Ok, just tried on my linux, here goes...

**Comment by ghost** [comment]
Oh it worked! Thank you so much for your help!

**Comment by adriweb** [comment]
Great! 
Which software on linux did you use to transfer it, TILP?
