### ISSUE TITLE
New cesium file

### ISSUE THREAD

**Issue by WatchMeFadee** [CE-Programming/libraries#44]
There seems to be a problem with the English version of cesium at the moment as when i attempt to launch cesium it clears my ram and restarts the calculator, this only happens  with the base cesium file but when i use the french one it works flawlessly, not the biggest issue but definitely something to look at, below is the cesium file i use.

[cesium.zip](https://github.com/CE-Programming/libraries/files/12458403/cesium.zip)

**Comment by mateoconlechuga** [comment]
Please reset your calculator fully ([2nd][mem] - Reset All) and then try installing Cesium.
