### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by daniell0999** [CE-Programming/libraries#47]
It isnt really an issue, but some programms only work with the new libary and some only with the old. Is it possible that you make a libary for that combines the old and the new?

**Comment by adriweb** [comment]
No, but also that shouldn't happen in the first place (libs are made to be compatible), and might indicate an issue with the programs themselves, or how they were made. 

Which are the programs in question?

**Comment by daniell0999** [comment]
Just some games from cemetech. When i try to Launch Games that only work in the new Release on the old Version they crash my calculator and it restarts with RAM cleared. And Vice versa

**Comment by adriweb** [comment]
Can you say which games exactly?

**Comment by daniell0999** [comment]
All Games, it doesnt even get recognized

Adrien Bertrand ***@***.***> schrieb am So., 29. Sept. 2024,
10:16:

**Comment by adriweb** [comment]
That doesn't make sense. You're saying some games crash. So first they'd have to be recognized for you to be able to launch them and see them crash. So, which ones?

**Comment by adriweb** [comment]
(Most importantly, we'd be interested in knowing which ones need old libraries specifically so that we could attempt fixing them as they must be doing something wrong)

**Comment by daniell0999** [comment]
Sorry wrong conversation, yeah it only Happens with some Programms. I cant
really Take names since its been half a year already

Adrien Bertrand ***@***.***> schrieb am So., 29. Sept. 2024,
10:30:

**Comment by adriweb** [comment]
Ok well if you find out about one, let us know here

**Comment by daniell0999** [comment]
But you can try yourself, Just Download a few Games of cemetech and you will get the Same issue

**Comment by adriweb** [comment]
I mean we regularly test dozens of programs/games. And there's more than 450k downloads of the clibs total, so it must not be a very common issue otherwise more people would complain.

We've seen like two or three things that were made in ICE that did crash because the ice code was doing something wrong and this isn't really fixable at this point, but it wasn't even a game iirc

**Comment by daniell0999** [comment]
Ima send a Video soon

Adrien Bertrand ***@***.***> schrieb am So., 29. Sept. 2024,
10:38:

**Comment by daniell0999** [comment]
https://github.com/user-attachments/assets/e8984f8d-0a5e-43fc-b59b-5c4445e2ee51
This what Happens when i Run it in a newer Version, it works fine on older

**Comment by adriweb** [comment]
Ok so this file https://www.cemetech.net/downloads/files/1598/x1598
maybe @mateoconlechuga can identify which part is triggering a crash. But anyway this is some 7-year old thing without the source code (?), so I'm not too hopeful, if the author isn't around here anymore.

**Comment by daniell0999** [comment]
Yeah, also Like marianas trench, Game, it Just also Crashes, and a Lot
more, ima Just too lazy to search again Just of my memory from half a year
ago

Adrien Bertrand ***@***.***> schrieb am So., 29. Sept. 2024,
11:07:

**Comment by adriweb** [comment]
Ok so https://www.cemetech.net/downloads/files/1611/x1611 .
Same author, same time-frame.... and both using some (probably too old) version of ICE that makes it crash. So this was indeed identified some time ago, but nothing we can really do about it. The author of ICE isn't active anymore :(

**Comment by daniell0999** [comment]
Wait ist it the Same Autor of SAMM? Cause that Crashes too

Adrien Bertrand ***@***.***> schrieb am So., 29. Sept. 2024,
11:14:

**Comment by adriweb** [comment]
SAMM... is actually launching correctly, but crashing when starting a new game or something?
So, might not even be related to the libraries (I've tested some old lib versions too and they appear to crash similarly)

However, the author is still around! I've asked here: https://www.cemetech.net/forum/viewtopic.php?p=308676#308676

**Comment by daniell0999** [comment]
So is it Just an authors Problem?

Adrien Bertrand ***@***.***> schrieb am So., 29. Sept. 2024,
11:31:

**Comment by adriweb** [comment]
_Probably_ a coding mistake on their end, yes. With a bit of luck, it should be easy enough to fix in a new version. I've also pinged them on Discord, so, we'll see.
