### ISSUE TITLE
Breaks Python on TI 84 Plus CE Python Edition

### ISSUE THREAD

**Issue by theswordsgame** [CE-Programming/libraries#48]
Title is self explanatory when installed on a python edition calculator the python app becomes unusable specifically it cause the calculator to soft lock when running programs requiring a ram reset.

**Comment by adriweb** [comment]
Can you give more details?
- What version of the libraries did you use?
- Which program used the libraries?
- Which calculator exactly ("TI-84 Plus CE Python" or "TI-84 Plus CE-T Python Edition") and in [which datecode-revision](https://i.imgur.com/4t0GQfk.jpeg) ?

**Comment by theswordsgame** [comment]
The latest version
Just installing the libraries causes issues but I tested a minesweeper game
Old Style date code TI-84 Plus CE Python

**Comment by mateoconlechuga** [comment]
You aren't giving enough information to reproduce the issue. What are the steps? What minesweeper game? What Python thing are you doing? Please assume we know nothing about your issue.

**Comment by theswordsgame** [comment]
I first reset the calculator than I installed the latest os, then I installed artifice and asmhook and after I installed the clibs running programs in the python app on my calculator would freeze it. I used https://cemetech.net/downloads/files/1450/x3066 to test if asmhook was working

**Comment by adriweb** [comment]
Just so you know: the thing is that "installed the clibs" doesn't really mean anything, since there is no installation. So I suppose you mean just transferring them. But that itself doesn't matter since it's just adding files to your archive memory. So the real problem is either in some of the library functions when called by the game in question, or directly in the game itself.

**Comment by theswordsgame** [comment]
Yeah transferring is probably the better way to describe it but the issue is happening before I even transfer any game or app to the calc it happens after transferring the clibs

**Comment by adriweb** [comment]
If you do this, does it "solve" it?
(Assuming you have the latest version of everything)

- ram reset
- Transfer clibs (and potentially some other programs) but don't run anything
- Try the Python app
- Launch artifice and quit it
- try the Python app again
- If it works, artifice and asmhook
- Python again?
- Some game
- Python again ?

**Comment by leandromaxwell2012-max** [comment]
@theswordsgame https://github.com/CE-Programming/toolchain/issues/814#issuecomment-5639726595
