### ISSUE TITLE
clibs.8xg crashing ti-connect

### ISSUE THREAD

**Issue by TenderGalaxy** [CE-Programming/libraries#50]
clibs.8xg crashes TI-Connect, it says "clibs.8xg is broken" and it refuses to load anything. os is 5.7.0.0021

**Comment by TenderGalaxy** [comment]
Or I didn't download aritifice... I'm going to check my OS

**Comment by adriweb** [comment]
Which TI Connect version exactly ?
On which computer? And OS version?
Have you tried re-downloading the latest clibs.8xg in case your download got corrupted?

**Comment by TenderGalaxy** [comment]
> Which TI Connect version exactly ? On which computer? And OS version? Have you tried re-downloading the latest clibs.8xg in case your download got corrupted?

1. I dunno, I downloaded it like 2 weeks ago
2. Macbook air Sonoma 14.3
3. yes

**Comment by adriweb** [comment]
Ok, are you sure it's TI Connect CE ?
(Not just TI Connect (that's old, you should uninstall that))

And you're either doing a drag-n-drop of the file onto the calc's name in side (not trying to open the file with TI Connect ce, that wouldn't work) or using the menu/button to send a file to the calc) ?
