### ISSUE TITLE
Filled Rectangles w/ Negative Width/Height

### ISSUE THREAD

**Issue by spenceboy98** [CE-Programming/libraries#8]
I use filled rectangles for my Fuel bar and Health bar in Catylizm. Whenever the height gets to <= 0, it does this:
![rectangle bug](https://cloud.githubusercontent.com/assets/3201577/13370583/2eec4af6-dcda-11e5-8665-449e03ddb19f.gif)
It looks worse on the emu and on the real calc. It flickers and doesn't look very good.

**Comment by mateoconlechuga** [comment]
But... How can you have a negative height? That's not a part of the library system. I guess I could add checks in for negativity :)

**Comment by mateoconlechuga** [comment]
Note: Widths must be greater than or equal to 2. This also needs to be fixed.

**Comment by mateoconlechuga** [comment]
Negative and 0 widths are now properly handled. Heights of 0 and down to -14 are also handled. Please note that the prototype technically doesn't allow negatives though :)

**Comment by jacobly0** [comment]
Removed handling of negative heights and widths (to fix #11).  If you need negative widths use a clipped routine (which takes signed arguments) or check for that case yourself.
